### ISSUE TITLE
saLTIre says JWT signature check failed - perhaps an invalid public key or timestamp

### ISSUE THREAD

**Issue by tomwjerry** [celtic-project/Rating-PHP#11]
I configured this project on a docker localhost image and cannot submit items to saLTIre, I got the error message (JWT signature check failed - perhaps an invalid public key or timestamp).
I set up saLTIre like this:
LTI version: 1.3.0
Message URL: http://localhost (doesn't seem to do anything)
Initiate login URL: http://localhost/connect.php
Redirection URI(s): http://localhost
http://localhost/connect.php
http://localhost/jwks.php
Public keyset URL: http://localhost/jwks.php (the Fetch button doesn't work, but might be because of localhost.)

As for the tool admin, I set it up like this:
Platform ID: https://saltire.lti.app/platform
Client ID: saltire.lti.app
Deployment ID: like saLTIre
Authorization server ID: left empty
Authentication request URL: https://saltire.lti.app/platform/auth
Access token URL: using the Access Token service URL
Public key: directly copy and paste from saLTIre
JSON webkey URL (jku): empty
Enabled?: check
remaining stuff empty

I also filled in config.php the stuff there, copy private key, KID and everything and paste.
I also tried different variants to fill the tool Public key in the bottom using the direct call to http://localhost/jwks.php and copy the json there.
Nothing seems to work and I am stuck at after Create content item, it takes me back to saLTIre and shows JWT signature check failed - perhaps an invalid public key or timestamp. Dunno if this is an issue with the rating tool or the LTI-PHP framework. If anyone had succeed submitting an item, let me know what different setup you used. Thank you!

**Comment by spvickers** [comment]
I assume this issue has now been resolved; if not, please respond with an update.
