### ISSUE TITLE
Will there be an update using platform storage?

### ISSUE THREAD

**Issue by kylejtuck** [celtic-project/Rating-PHP#12]
Thank you so much for this example. I have been able to implement and adapt it to simply show user details from userResult in onLaunch.

However, your example (and my adaptations) use $_SESSION which doesn't work where cross-site tracking is disabled (unless I'm missing something).

It appears the library supports platform storage. Any chance the example could be updated? I have tried to figure this out but can't seem to wrap my head around it.

**Comment by kylejtuck** [comment]
So, your existing example should be working when cookies are blocked?

**Comment by spvickers** [comment]
Yes, assuming you are using a version of the library in which this feature has been added.

**Comment by spvickers** [comment]
The implemented solution will force the tool into a new tab/window as a last resort.  However, as browsers increase their restrictions on third-party cookies, even this may prove to be insufficient.  Tools may need to completely avoid their dependence upon cookies to carry on working, but if you know of any other techniques which can be usefully implemented, please pass them on.
