### ISSUE TITLE
name role provision doesnt weem to work

### ISSUE THREAD

**Issue by JacquesMiov** [celtic-project/Rating-PHP#13]
Hi Stephen
I've got the thing up and running, but when I click on user list nothing appears. Is this working? Is there something I'm missing from a config on the moodle side perhaps? I've got some student roles enrolled on the course but their details don't pass through.
Thanks

**Comment by spvickers** [comment]
It should be working; check the log files for clues, especially those of your platform to see whether it received a request for a list of users and, if so, how it responded.

**Comment by JacquesMiov** [comment]
on the rating page i see this
Your course appears to offer the ability to access a list of users. 

when i press show user list i get this
Your course does not appear to offer the ability to access a list of groups, or there are no group sets available.

all of the settings for the lti tool setup are coorrect i think. privacy set to always send, the nprs is enabled.
there don't appear to be any logs throwing errors but i do get this through php loggin
Warning: openssl_sign(): Supplied key param cannot be coerced into a private key in /var/www/autosentia.com/html/rate/vendor/firebase/php-jwt/src/JWT.php on line 254


and this
eprecated: Accessing static trait property ceLTIc\LTI\ApiHook\ApiHook::$MEMBERSHIPS_SERVICE_HOOK is deprecated, it should only be accessed on a class using the trait in /var/www/autosentia.com/html/rate/lib.php on line 24

Deprecated: Accessing static trait property ceLTIc\LTI\ApiHook\ApiHook::$USER_ID_HOOK is deprecated, it should only be accessed on a class using the trait in /var/www/autosentia.com/html/rate/lib.php on line 25

Deprecated: Accessing static trait property ceLTIc\LTI\ApiHook\ApiHook::$MEMBERSHIPS_SERVICE_HOOK is deprecated, it should only be accessed on a class using the trait in /var/www/autosentia.com/html/rate/lib.php on line 26

thanks

**Comment by spvickers** [comment]
So it looks like there is a problem with your private key.  Is your JWKS endpoint returning a public key?

**Comment by JacquesMiov** [comment]
many thanks! i hadn't put the private key in. cheers you're a legend.
