### ISSUE TITLE
postgres database error? 

### ISSUE THREAD

**Issue by JacquesMiov** [celtic-project/Rating-PHP#14]
when i delete an item from the admin screen i get this. is this a problem with how i've set up the pgsql as i had to imgaine a lot when doing it because your guidance is for mysql and i don't think its compatible with postgres.

the database is setup like this

Column      |            Type             | Collation | Nullable |                Default      
------------------+-----------------------------+-----------+----------+---------------------------------------
 item_pk          | integer                     |           | not null | nextval('item_item_pk_seq'::regclass)
 resource_link_pk | integer                     |           | not null |
 item_title       | character varying(200)      |           | not null |
 item_text        | text                        |           |          |
 item_url         | character varying(200)      |           |          |
 max_rating       | integer                     |           | not null | 5
 step             | integer                     |           | not null | 1
 visible          | boolean                     |           | not null | false
 sequence         | integer                     |           | not null | 0
 created          | timestamp without time zone |           | not null | CURRENT_TIMESTAMP
 updated          | timestamp without time zone |           | not null | CURRENT_TIMESTAMP
Indexes:
    "item_pkey" PRIMARY KEY, btree (item_pk)
Foreign-key constraints:
    "item_lti_resource_link_fk1" FOREIGN KEY (resource_link_pk) REFERENCES lti2_resource_link(resource_link_pk) ON UPDATE CASCADE
Referenced by:
    TABLE "rating" CONSTRAINT "rating_item_fk1" FOREIGN KEY (item_pk) REFERENCES item(item_pk)

Fatal error: Uncaught PDOException: SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist: boolean = integer LINE 4: WHERE (i.resource_link_pk = $1) AND (i.visible = 1) ^ HINT: No operator matches the given name and argument types. You might need to add explicit type casts. in /var/www/.com/html/rate/lib.php:568 Stack trace: #0 /var/www/.com/html/rate/lib.php(568): PDOStatement->execute() #1 /var/www/.com/html/rate/lib.php(482): getVisibleRatingsCounts() #2 /var/www/.com/html/rate/index.php(94): updateGradebook() #3 {main} thrown in /var/www/.com/html/rate/lib.php on line 568

many thanks

**Comment by spvickers** [comment]
Whilst the LTI library supports multiple databases, including PostgreSQL, this app was written for MySQL.  To run it using a different database will require all the database-related code within the app (especially the SQL statements) to be checked to make sure it works with the selected database.  For example, your error message shows an incompatibility between using boolean and integer data types in PostgreSQL and MySQL respectively.
