### ISSUE TITLE
Score lines repeated whenever an item is hidden and unhidden, and not deleted when deleting activity

### ISSUE THREAD

**Issue by igorbga** [celtic-project/Rating-PHP#2]
Not sure if this is really a bug or if is it just that this demo app is just ignoring some edge cases that a real app should manage.

Rating demo app: Master branch of July 3rd, 2020
Library version: 4.0.1

I have configured a moodle activity to use the rating app as external tool. I have instructed moodle to allow Grades and columns Sync so that the Rating demo application can send not just the global activity score but a lineItem score per item.

Each time an item is hidden and shown back a new lineItem is created so that scoring in moodle are repeated. I think this is not expected behaviour. I guess the score column for the item in moodle should be deleted or just left as is, but in that last case no new score column should be created when the item is made visible again.

I've also seems that when I delete the activity in moodle the general activity score column is deleted, but not the score columns that are create per each item.

**Comment by igorbga** [comment]
Some more feedback on this issue:

If I delete a item as a teacher its scoring column in moodle dissapears, that works ok. But when an item is hidden it creates a new one with the same name. If you then delete de hidden item the first column is deleted but not the duplicated one. So probably the problem is that it should just not create a new score column (lineItem?) when hidden.

When the activity is deleted as already stated no item scores are deleted, but I guess this is just something to be expected as I suppose that moodle will not communicate the deletion of the activity to the Rating tool.

**Comment by spvickers** [comment]
Thanks, the use of the LineItem service was a late addition to the app to illustrate how it works and clearly needs some attention to handle such cases.

**Comment by spvickers** [comment]
This should be resolved in the latest commit.
