### ISSUE TITLE
Guide for setting up in local

### ISSUE THREAD

**Issue by adydev15** [celtic-project/Rating-PHP#6]
Hi ,

Sorry for if it sounds some what silly but i am newbie with LTI and looking for a solution Integrated LTI with Laravel as LMS. Though i didnt find any guidance on this or insights how it can be integrated with Laravel and how it can be used.

LTI is new to me and still i am checking and learning about LTI.

As my requirement is with LTI 1.1 .

I have tried setting up this in local but i dont know if i have configured upto mark as it is throwing error.

If a guide for usage in somewhat details would be there then it would be good.

I have set up it in local i can access admin and can create platforms.

But i am having error when i access index.php  **ERROR: Unable to open session.**

I also try to access app_name/connect.php  : **Error
Sorry, there was an error connecting you to the application.**

Dont know if i am doing right any guidance would be helpful.

Thanks n Regards

**Comment by adydev15** [comment]
Thanks @spvickers for explanation regarding laravel.

For the rest of two answers for my questions ..do you mean that it needs to be called via external request and cant be tested locally or is there a way i can follow that to check how it functions.. ?

**Comment by spvickers** [comment]
No, I do not mean that, you should be able to run everything locally.  But accessing index.php requires you to have logged in first and this is done via a LTI launch message sent to the connect.php endpoint.

**Comment by adydev15** [comment]
ok !

Pardon but i dont know how LTI Launch message will work so it can sent message to connect.php or do i have to set manually in file to check things..

For Index.php i got that we need to login and also the session needs to be set before it functions normal.

**Comment by spvickers** [comment]
LTI is a specification designed to allow a platform (such as a VLE/LMS) to seamlessly and securely connect users to a tool.  This Rating app is an LTI tool, so you need to use it in conjunction with an LTI platform.  This can be any platform which supports LTI such as Moodle, Sakai, Blackboard Learn, Canvas, Brightspace.  There is also a testing platform named saLTIre which is available at https://saltire.lti.app/platform.  HTH.

**Comment by adydev15** [comment]
ok thank you for detailed explanation much appreciated !
