### ISSUE TITLE
Firebase\JWT\JWT as JWT because the name is already in use

### ISSUE THREAD

**Issue by drewbie24** [celtic-project/Rating-PHP#7]
Having difficulty with making use of firebase and the jwt class from the php library having conflicting names. Particulary found in the FirebaseClient.php file

How do i resolve the issues of this?

**Comment by spvickers** [comment]
As with any other namespace in PHP you can always refer to a class using a fully-qualified reference (e.g. \ceLTIc\LTI\Jwt\Jwt and \Firebase\JWT\JWT), or a partially qualified name in conjunction with a use statement, or use an as reference.  See https://www.php.net/manual/en/language.namespaces.importing.php for more details.
